defmodule Ashie.Repo.Migrations.CreateStudentUniqueIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:students, [:student_id, :firstname, :lastname],
             name: "students_unique_student_id_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:students, [:student_id, :firstname, :lastname],
                     name: "students_unique_student_id_name_index"
                   )
  end
end
