defmodule Ashie.Repo.Migrations.CreateStudents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:students, primary_key: false) do
      add :student_id, :citext, null: false, primary_key: true
      add :firstname, :citext, null: false
      add :lastname, :citext, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:students, [:student_id], name: "students_unique_student_id_index")
  end

  def down do
    drop_if_exists unique_index(:students, [:student_id],
                     name: "students_unique_student_id_index"
                   )

    drop table(:students)
  end
end
